### ISSUE TITLE
Status of preference window?

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#74]
Is the preference window currently working? Here, when selecting the add-on preferences, the last view will stay active.

![grafik](https://github.com/windingwind/zotero-plugin-template/assets/4668198/e3617bf6-d500-4485-9330-5df652876f7c)

**Comment by windingwind** [comment]
Yes, it's working for me. Are you using the `release` version? The release might be outdated (but building from source always works). I've just pushed a new release.

**Comment by denismaier** [comment]
I don't think I'm using the release version. I've set up the environment following these instructions: https://github.com/windingwind/zotero-plugin-template#setup-development-environment

**Comment by windingwind** [comment]
Which branch are you on? I need more details.

Generally, you run into this because of missing locales. Are you changing the `preference.xhtml` or `locale/*.ftl`?

**Comment by denismaier** [comment]
Main branch: https://github.com/denismaier/zotero-plugin-test
No, I did not change those files. 
Locales may be an issue. The error console complains about missing locale files. I've already switched to en-US, but it's still not working. And, in other cases it would just use the terms from en-US even though the language is set to de-DE.

**Comment by denismaier** [comment]
Error messages:

![grafik](https://github.com/windingwind/zotero-plugin-template/assets/4668198/631287e4-8501-4cdf-9371-0e698c19e1cc)

**Comment by windingwind** [comment]
What's your Zotero version? We need beta12 or higher.

Providing a debug output would help us understand your case better.

**Comment by denismaier** [comment]
7.0.0-beta.50+8239d04d5

Debug output:

```

1699630831867	addons.xpi	WARN	Checking C:\Zotero7_beta\distribution\extensions for addons

1699630831932	addons.xpi-utils	WARN	addMetadata: Add-on undefined is invalid: Error: Invalid addon ID: expected addon ID undefined, found undefined in manifest(resource://gre/modules/addons/XPIDatabase.jsm:2972:15) JS Stack trace: addMetadata@XPIDatabase.jsm:2972:15
processFileChanges@XPIDatabase.jsm:3433:26
checkForChanges@XPIProvider.jsm:3065:55
startup@XPIProvider.jsm:2492:12
callProvider@AddonManager.jsm:234:31
_startProvider@AddonManager.jsm:542:17
startup@AddonManager.jsm:748:14
startup@AddonManager.jsm:3468:26
observe@addonManager.js:78:29

[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 2652 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2652:33
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1053 getUpdateFile
resource://gre/modules/UpdateService.jsm 732 getCanApplyUpdates
resource://gre/modules/UpdateService.jsm 3725 get canUsuallyApplyUpdates
resource://gre/modules/UpdateService.jsm 3733 get canApplyUpdates
resource://gre/modules/UpdateService.jsm 2654 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getUpdateFile@resource://gre/modules/UpdateService.jsm:1053:32
getCanApplyUpdates@resource://gre/modules/UpdateService.jsm:732:39
get canUsuallyApplyUpdates@resource://gre/modules/UpdateService.jsm:3725:12
get canApplyUpdates@resource://gre/modules/UpdateService.jsm:3733:1
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2654:9
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1053 getUpdateFile
resource://gre/modules/UpdateService.jsm 4122 UM__loadXMLFileIntoArray
resource://gre/modules/UpdateService.jsm 4017 UpdateManager
resource://gre/modules/XPCOMUtils.jsm 161 XPCU_serviceLambda
resource://gre/modules/XPCOMUtils.jsm 62 get
resource://gre/modules/UpdateService.jsm 2668 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getUpdateFile@resource://gre/modules/UpdateService.jsm:1053:32
UM__loadXMLFileIntoArray@resource://gre/modules/UpdateService.jsm:4122:29
UpdateManager@resource://gre/modules/UpdateService.jsm:4017:28
XPCU_serviceLambda@resource://gre/modules/XPCOMUtils.jsm:161:30
get@resource://gre/modules/XPCOMUtils.jsm:62:51
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2668:9
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 4024 UpdateManager
resource://gre/modules/XPCOMUtils.jsm 161 XPCU_serviceLambda
resource://gre/modules/XPCOMUtils.jsm 62 get
resource://gre/modules/UpdateService.jsm 2668 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
UpdateManager@resource://gre/modules/UpdateService.jsm:4024:33
XPCU_serviceLambda@resource://gre/modules/XPCOMUtils.jsm:161:30
get@resource://gre/modules/XPCOMUtils.jsm:62:51
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2668:9
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1786 pingStateAndStatusCodes
resource://gre/modules/UpdateService.jsm 2801 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
pingStateAndStatusCodes@resource://gre/modules/UpdateService.jsm:1786:5
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2801:28
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1053 getUpdateFile
resource://gre/modules/UpdateService.jsm 4122 UM__loadXMLFileIntoArray
resource://gre/modules/UpdateService.jsm 4216 _getUpdates
resource://gre/modules/UpdateService.jsm 4260 addUpdateToHistory
resource://gre/modules/UpdateService.jsm 1365 cleanupReadyUpdate
resource://gre/modules/UpdateService.jsm 2920 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getUpdateFile@resource://gre/modules/UpdateService.jsm:1053:32
UM__loadXMLFileIntoArray@resource://gre/modules/UpdateService.jsm:4122:29
_getUpdates@resource://gre/modules/UpdateService.jsm:4216:33
addUpdateToHistory@resource://gre/modules/UpdateService.jsm:4260:24
cleanupReadyUpdate@resource://gre/modules/UpdateService.jsm:1365:8
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2920:7
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1370 cleanupReadyUpdate
resource://gre/modules/UpdateService.jsm 2920 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
cleanupReadyUpdate@resource://gre/modules/UpdateService.jsm:1370:24
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2920:7
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown
You may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157
resource://gre/modules/FileUtils.jsm 70 FileUtils_getDir
resource://gre/modules/UpdateService.jsm 1014 getUpdateDirCreate
resource://gre/modules/UpdateService.jsm 1095 getReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1267 cleanUpReadyUpdateDir
resource://gre/modules/UpdateService.jsm 1375 cleanupReadyUpdate
resource://gre/modules/UpdateService.jsm 2920 AUS__postUpdateProcessing
resource://gre/modules/UpdateService.jsm 2543 AUS_observe
resource://gre/modules/UpdateServiceStub.jsm 113 UpdateServiceStub
" {file: "resource://gre/modules/Deprecated.jsm" line: 86}]
warning@resource://gre/modules/Deprecated.jsm:86:8
FileUtils_getDir@resource://gre/modules/FileUtils.jsm:70:20
getUpdateDirCreate@resource://gre/modules/UpdateService.jsm:1014:20
getReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1095:10
cleanUpReadyUpdateDir@resource://gre/modules/UpdateService.jsm:1267:17
cleanupReadyUpdate@resource://gre/modules/UpdateService.jsm:1375:3
AUS__postUpdateProcessing@resource://gre/modules/UpdateService.jsm:2920:7
AUS_observe@resource://gre/modules/UpdateService.jsm:2543:20
UpdateServiceStub@resource://gre/modules/UpdateServiceStub.jsm:113:9


[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36


[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "originalThis.item is undefined" {file: "file:///C:/Users/denis/dateien/2-bereiche/ub/dev/zotero-plugin-test/build/addon//chrome/content/scripts/testaddon.js" line: 5015}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\denis\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12


[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "The connection to wss://stream.zotero.org/ has terminated unexpectedly. Some data may have been transferred."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection to wss://stream.zotero.org/ has terminated unexpectedly. Some data may have been transferred."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

appName => Zotero, version => 7.0.0-beta.50+8239d04d5, os => Windows 10.0 22621, locale => en-US, extensions => Zotero Test Addon (1.0.0, extension)

(3)(+0828553): Attaching <checkbox> element to extensions.zotero.automaticScraperUpdates

(3)(+0000000): Attaching <checkbox> element to extensions.zotero.reportTranslationFailure

(3)(+0000000): Attaching <html:input> element to extensions.zotero.baseAttachmentPath

(3)(+0000000): Attaching <radiogroup> element to extensions.zotero.useDataDir

(3)(+0000000): Attaching <html:input> element to extensions.zotero.dataDir

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.newItem

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.newNote

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.library

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.quicksearch

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.copySelectedItemCitationsToClipboard

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.copySelectedItemsToClipboard

(3)(+0000000): Attaching <html:input> element to extensions.zotero.keys.toggleAllRead

(3)(+0000000): Attaching <menulist> element to extensions.zotero.feeds.sortAscending

(3)(+0000000): Attaching <html:input> element to extensions.zotero.fulltext.textMaxLength

(3)(+0000000): Attaching <html:input> element to extensions.zotero.fulltext.pdfMaxPages

(4)(+0000003): SELECT COUNT(*) FROM fulltextItems WHERE synced != ? AND ((indexedPages IS NOT NULL AND indexedPages=totalPages) OR (indexedChars IS NOT NULL AND indexedChars=totalChars)) [4]

(4)(+0000002): SELECT COUNT(*) FROM fulltextItems WHERE (indexedPages IS NOT NULL AND indexedPages<totalPages) OR (indexedChars IS NOT NULL AND indexedChars<totalChars)

(4)(+0000000): SELECT COUNT(*) FROM itemAttachments WHERE itemID NOT IN (SELECT itemID FROM fulltextItems WHERE synced != ? AND (indexedPages IS NOT NULL OR indexedChars IS NOT NULL)) [4]

(4)(+0000001): SELECT COUNT(*) FROM fulltextWords

(3)(+0024904): HTTP POST "1699630831867 addons.xpi WARN …" (18093 chars) to https://repo.zotero.org/repo/report?debug=1

(3)(+0000003): POST body gzipped from 18093 to 2341; 87% savings

(3)(+0000840): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200

```

**Comment by windingwind** [comment]
Thanks for pointing out - this is a missing locale in `en-US/preferences.ftl`. I've fixed that.

Please sync your repo with the main branch and try again.

**Comment by denismaier** [comment]
Thanks for the fix. I'll give it shot and report.

**Comment by denismaier** [comment]
> Please sync your repo with the main branch and try again.

Oh, this actually leads to a question regarding the suggested workflow. I've used the `Use this template` button, which doesn't seem to create a fork, but rather an indipendent copy of the repo. Is that how it should be done? (And how would you sync in that case?)

**Comment by windingwind** [comment]
Even if you build your plugin as a fork, after releasing your plugin, you'll definitely have tons of commits to the branch and as well need to manually check because of the conflicts. You'll have to manually check the git commit history and do corresponding changes to my plugins when necessary. 

But having to update the template is a rare case:

1. Generally, we only add new examples/small fixes to the template, which will never be used in a real plugin. You don't need to follow these changes
2. If there are significant changes that we think it is necessary or very useful, like the hot reload, we will give instructions for what you'll have to do, like https://github.com/windingwind/zotero-plugin-template#auto-hot-reload

If you really want to merge the changes from the original repo, you can locally add the original repo to the git remote and then merge/cherry-pick the commits locally as you like.

BTW, I enabled the `use this template` because people can easily try it out in the codespace.

**Comment by denismaier** [comment]
So, basically you suggest not to track the upstream repo slavishly, but rather to copy only what is really needed.

I've now added the one added line from the last commit to `preferences.ftl`, and the preference window is now working. Thanks for your help again!

**Comment by windingwind** [comment]
Glad to know :)
